#!/usr/bin/env bash
# bump-version.sh — Update the version string everywhere it lives.
#
# Usage:
#   ./scripts/bump-version.sh 1.13.0           # dry-run, shows planned edits
#   ./scripts/bump-version.sh 1.13.0 --apply   # writes the edits and runs npm install
#
# Files touched (nine version locations):
#   src-tauri/Cargo.toml          (Rust package version of the Tauri app)
#   src-tauri/tauri.conf.json     (Tauri config — drives bundle / installer naming)
#   service-tool/Cargo.toml       (Windows privileged service)
#   helper-tool/Cargo.toml        (macOS privileged helper)
#   package.json                  (npm package metadata)
#   build-pkg.sh                  (macOS pkg builder VERSION variable)
#   installer-iss/installer.iss   (Inno Setup AppVersion)
#   src/index.html                (UI signature version display)
#   README.md                     (version in the footer signature line)
#
# package-lock.json is regenerated automatically by `npm install` after edits.
# dist/index.html is regenerated by the next `npm run tauri build` — not touched here.

set -euo pipefail

# --- Locate repo root regardless of where the script is invoked from ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${REPO_ROOT}"

# --- Args ---
if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <new-version> [--apply]" >&2
    echo "Example: $0 1.13.0 --apply" >&2
    exit 1
fi

NEW_VERSION="$1"
APPLY=false
if [[ "${2:-}" == "--apply" ]]; then
    APPLY=true
fi

# --- Validate semver shape ---
if ! [[ "${NEW_VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "ERROR: '${NEW_VERSION}' is not a valid semver (expected X.Y.Z)" >&2
    exit 1
fi

# --- Refuse to run on a dirty working tree (when applying) ---
if ${APPLY}; then
    if ! git diff --quiet || ! git diff --cached --quiet; then
        echo "ERROR: working tree has uncommitted changes." >&2
        echo "       Commit or stash first, so the version bump lands as a clean diff." >&2
        exit 1
    fi
fi

# --- The edits, expressed as (file, sed-pattern, sed-replacement) triples ---
# Each entry: a file path and a sed command. The patterns are tight enough
# to only match the intended line — we don't want to clobber dependency
# version specs that happen to share a number.
#
# Note on sed -i: GNU sed wants -i'' (empty backup), BSD sed (macOS default)
# wants -i '' (empty backup as a separate arg). Using a tmpfile dance keeps
# us portable across both without `-i` quirks.

edit_file() {
    local file="$1"
    local pattern="$2"
    local label="$3"

    if [[ ! -f "${file}" ]]; then
        echo "  SKIP ${file} (not found)"
        return
    fi

    local current
    current="$(grep -Eo "${pattern}" "${file}" | head -1 || true)"
    if [[ -z "${current}" ]]; then
        echo "  WARN ${file}: pattern '${pattern}' did not match anything"
        return
    fi

    echo "  ${label}: ${file}"
    echo "        match : ${current}"

    if ${APPLY}; then
        local tmp
        tmp="$(mktemp)"
        sed -E "s|${pattern}|${REPLACEMENT}|" "${file}" > "${tmp}"
        mv "${tmp}" "${file}"
    fi
}

echo "Version bump: ${NEW_VERSION}"
echo "Mode: $(${APPLY} && echo APPLY || echo dry-run)"
echo ""
echo "Editing files:"

# Cargo.toml (all three crates) — `version = "X.Y.Z"` on the line after [package]
REPLACEMENT="version = \"${NEW_VERSION}\""
edit_file "src-tauri/Cargo.toml"       'version = "[0-9]+\.[0-9]+\.[0-9]+"' "Cargo (src-tauri)"
edit_file "service-tool/Cargo.toml"    'version = "[0-9]+\.[0-9]+\.[0-9]+"' "Cargo (service-tool)"
edit_file "helper-tool/Cargo.toml"     'version = "[0-9]+\.[0-9]+\.[0-9]+"' "Cargo (helper-tool)"

# tauri.conf.json — `"version": "X.Y.Z",`
REPLACEMENT="\"version\": \"${NEW_VERSION}\""
edit_file "src-tauri/tauri.conf.json"  '"version": "[0-9]+\.[0-9]+\.[0-9]+"' "Tauri config"

# package.json — same pattern, but multiple lines could match; only the top-level
# `"version":` should be touched. Anchor it to occur before "scripts" (i.e. early).
# Simplest approach: only match if preceded by a 2-space indent that's at top level.
REPLACEMENT="\"version\": \"${NEW_VERSION}\""
edit_file "package.json"               '"version": "[0-9]+\.[0-9]+\.[0-9]+"' "npm package"

# build-pkg.sh — `VERSION="X.Y.Z"`
REPLACEMENT="VERSION=\"${NEW_VERSION}\""
edit_file "build-pkg.sh"               'VERSION="[0-9]+\.[0-9]+\.[0-9]+"' "build-pkg.sh"

# installer.iss — `#define AppVersion "X.Y.Z"`
REPLACEMENT="#define AppVersion \"${NEW_VERSION}\""
edit_file "installer-iss/installer.iss" '#define AppVersion "[0-9]+\.[0-9]+\.[0-9]+"' "Inno Setup"

# index.html signature — `<span class="signature-version">X.Y.Z</span>`
REPLACEMENT="<span class=\"signature-version\">${NEW_VERSION}</span>"
edit_file "src/index.html"             '<span class="signature-version">[0-9]+\.[0-9]+\.[0-9]+</span>' "UI signature"

# README.md — version in the footer signature line: `... · vX.Y.Z · ...`
# Match only the `v`-prefixed token so we never touch the versioned screenshot
# filename (e.g. `...(1.13.1).png`), which would break the image link.
REPLACEMENT="v${NEW_VERSION}"
edit_file "README.md"                  'v[0-9]+\.[0-9]+\.[0-9]+' "README footer"

echo ""

if ! ${APPLY}; then
    echo "Dry run complete. Re-run with --apply to write changes."
    exit 0
fi

# --- Refresh package-lock.json so its 'version' fields match package.json ---
echo "Regenerating package-lock.json via npm install..."
npm install --silent --no-audit --no-fund

echo ""
echo "Done. Suggested next steps:"
echo "  git status"
echo "  git diff                                # eyeball the version bumps"
echo "  git commit -am \"Bump version to ${NEW_VERSION}\""
echo "  git tag v${NEW_VERSION}                 # optional"
echo "  git push && git push --tags"